### ISSUE TITLE
GUI Filters not handling all character sets

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#104]
The filters do not correctly handle grouping of alerts by observable if the observable value has non-ascii characters in it.

Example, if an analyst trys to group the five alerts together that have hits on this observable:

![image](https://user-images.githubusercontent.com/3869452/88821732-04d8c680-d191-11ea-9b07-a1e504221110.png)

The filter displays:
![image](https://user-images.githubusercontent.com/3869452/88821956-423d5400-d191-11ea-93b9-656df4d1435e.png)

And the grouping fails (no alerts result from the filter).

**Comment by KarmaPenny** [comment]
The new filter code and the old filter code both seems to filter the observable value the same way.

new:
`
conditions.append(self.value_column.like(f"%{value[1]}%".encode('utf8', errors='ignore')))
`

old:
`
observable_search.value.like('%{}%'.format(filters[FILTER_TXT_SEARCH_OBSERVABLE_VALUE].value).encode('utf8', errors='ignore'))))
 `

my guess is that the observables are not all getting inserted as utf8 or that something odd happens to the format of the observable when it is passed from the JS code back to the python gui code

**Comment by KarmaPenny** [comment]
this might be the issue. Not sure yet what format comes out of that atob and |s64encode stuff
`
set_filters({'Observable':[['{{_observable.type}}',atob('{{_observable.value | s64encode}}')]]});
`

**Comment by KarmaPenny** [comment]
yep looks like atob doesn't handle utf8 properly

https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings

**Comment by unixfreak0037** [comment]
@seanmcfeely This issue should be fixed in the most reset merge. Can you confirm?

**Comment by seanmcfeely** [comment]
It's still not working... 

`commit a49829c48d8ea72b9dd0ad7846c812a517bb5241 (HEAD -> dev, upstream/dev, upstream/HEAD)`

Same results for `* file:1.意见反馈表-化妆品安全评估技术导则（征求意见稿）by 814.xls`

![image](https://user-images.githubusercontent.com/3869452/89323804-4d422980-d654-11ea-8087-d4edde52a4f4.png)


![image](https://user-images.githubusercontent.com/3869452/89323842-56cb9180-d654-11ea-80a1-882632211500.png)

**Comment by KarmaPenny** [comment]
Hmm, I'll have to take another look then. The one test I did seemed to work fine. Maybe the characters I tested were url encoded or something that bypassed the issue

**Comment by KarmaPenny** [comment]
<img width="562" alt="Screen Shot 2020-08-04 at 1 38 53 PM" src="https://user-images.githubusercontent.com/17435481/89326236-f8a0ad80-d657-11ea-8c92-fcca132b7ea7.png">

Hmm seems to work for me

**Comment by KarmaPenny** [comment]
Did you refresh your javascript?

**Comment by seanmcfeely** [comment]
I cleared browser cache and it still didn't work.

**Comment by KarmaPenny** [comment]
Wait I think I figured it out. I get the same thing you get when I click on an observable on the manage page but not when I click on it from the alert page. I think I forgot to apply the fix to both places

**Comment by seanmcfeely** [comment]
ah yea, that's it. It works when I click from the alert page.

**Comment by KarmaPenny** [comment]
cool, creating a fix for clicking for the manage page. I forgot you could click on them on that page

**Comment by KarmaPenny** [comment]
Okay, got a fix in on our side I'll let @unixfreak0037 handle the merge to open source.

**Comment by seanmcfeely** [comment]
Fixed! thanks again

![image](https://user-images.githubusercontent.com/3869452/89439681-893ec280-d718-11ea-915b-e854b35a2a6b.png)
